name: Register Package
on: [push, pull_request, workflow_dispatch]
jobs:
  register:
    name: Register Package
    runs-on: ubuntu-latest
    steps:
    - uses: lukasgrunwald/julia-register-local@master
      with:
        localregistry: git@github.com:lukasgrunwald/CondMatRegistry.git
        ssh_keys: |
           ${{ secrets.REGISTRY_DEPLOY }}
    